[platformio]
src_dir = .

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Optimized 40KB SRAM Tensor Arena configuration (runs in internal RAM on any ESP32-S3)
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DBOARD_HAS_PSRAM

; Automatic dependency resolution on clone / build
lib_deps =
    https://github.com/tanakamasayuki/Arduino_TensorFlowLite_ESP32.git
